aboutUs/urls.py
from django.contrib import admin
from django.urls import path
from . import views

def app_name(model):
    return model._meta.app_label

    
app_name = 'aboutUs'
urlpatterns = [
    path('',views.aboutUs,name='aboutUs'),
]

aceinteriors_backend/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('homepage.urls')),
    path('aboutUs',include('aboutUs.urls')),
    path('contactUs',include('contactUs.urls')),
    path('project/',include('project.urls')),
]

contactUs/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'contactUs'

urlpatterns = [
    path('',views.contactUs,name='contactUs')
]

homepage/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'homepage'
urlpatterns = [
    path('',views.index,name='index'),
]

project/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'project'
urlpatterns = [
    path('',views.project,name='project')
]

aboutUs/models.py
from django.db import models

# Create your models here.

contactUs/models.py
from django.db import models

# Create your models here.

homepage/models.py
from django.db import models

# Create your models here.

project/models.py
from django.db import models

# Create your models here.

aboutUs/views.py
from django.shortcuts import render

def aboutUs(request):
    return render(request,'aboutUs.html')

contactUs/views.py
from django.shortcuts import render

def contactUs(request):
    return render(request,'contactUs.html')

homepage/views.py
from django.shortcuts import render

def index(request):
    return render(request,'index.html')

project/views.py
from django.shortcuts import render

def project(request):
    return render(request,'project.html')

aboutUs/templates/aboutUs.html
{% extends 'base.html' %}

contactUs/templates/contactUs.html
{% extends 'base.html' %}

homepage/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Great+Vibes&family=Montserrat+Alternates:wght@200;300&display=swap');
        </style>
    <title>{% block title %}{% endblock title %}</title>
    <style>
        .carousel-item:after {
            content: "";
            display: block;
            position: absolute;
            top: 0;
            bottom: 0;
            left: 0;
            right: 0;
            background: rgba(0, 0, 0, 0.2);
        }
    </style>
</head>
<body>

    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg bg-dark navbar-dark py-3">
        <div class="container">
            <a href="{% url 'homepage:index' %}" class="navbar-brand fw-bold">ACE Interiors</a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navmenu">
                <span class="navbar-toggler-icon"></span>
            </button>
            {% with app_name=request.resolver_match.app_name %}
            <div class="collapse navbar-collapse" id="navmenu">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link  {% if app_name == 'homepage' %}fw-bold active{% endif %}" href="{% url 'homepage:index' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link  {% if app_name == 'project' %}fw-bold active{% endif %}" href="{% url 'project:project' %}">Projects</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link  {% if app_name == 'aboutUs' %}fw-bold active{% endif %}" href="{% url 'aboutUs:aboutUs' %}">About Us</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link  {% if app_name == 'contactUs' %}fw-bold active{% endif %}" href="{% url 'contactUs:contactUs' %}">Contact Us</a>
                    </li>
                </ul>
            </div>
            {% endwith %}
        </div>
    </nav>
    {% block content %}{% endblock %}

    <footer class="p-4 mt-4 bg-dark text-light position-relative">
        <div class="container">
            <p class="lead fw-bold">Copyright &copy; 2021 - ACE Interiors</p>
            <a href="#" class="position-absolute bottom-0 end-0 p-5">
                    <span class="svg-icon">
                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px"
                             viewBox="0 0 24 24" version="1.1">
                            <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                <polygon points="0 0 24 0 24 24 0 24"></polygon>
                                <rect fill="#FFFFFF" opacity="0.5" x="11" y="10" width="2" height="10" rx="1"></rect>
                                <path d="M6.70710678,12.7071068 C6.31658249,13.0976311 5.68341751,13.0976311 5.29289322,12.7071068 C4.90236893,12.3165825 4.90236893,11.6834175 5.29289322,11.2928932 L11.2928932,5.29289322 C11.6714722,4.91431428 12.2810586,4.90106866 12.6757246,5.26284586 L18.6757246,10.7628459 C19.0828436,11.1360383 19.1103465,11.7686056 18.7371541,12.1757246 C18.3639617,12.5828436 17.7313944,12.6103465 17.3242754,12.2371541 L12.0300757,7.38413782 L6.70710678,12.7071068 Z"
                                      fill="#FFFFFF" fill-rule="nonzero"></path>
                            </g>
                        </svg>
                    </span>
            </a>
        </div>
    </footer>
    

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    {% block javascript %}
    
    {% endblock %}
    
</body>
</html>

homepage/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}Homepage{% endblock %}
{% block content %}
<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active"
            aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1"
            aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2"
            aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="{% static 'img/1.jpg' %}" class="d-block w-100" alt="image1">
        </div>
        <div class="carousel-item">
            <img src="{% static 'img/2.jpg' %}" class="d-block w-100" alt="image2">
        </div>
        <div class="carousel-item">
            <img src="{% static 'img/3.jpg' %}" class="d-block w-100" alt="image3">
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators"
        data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators"
        data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>
<br><br>


<div class="card text-center">
    <h1 class="card-header" style="font-family: 'Montserrat Alternates', sans-serif;">Alerts/Updates</h1>
    <div class="card-body">
        <span>
            <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
                <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
                    <path
                        d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z" />
                </symbol>
                <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
                    <path
                        d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z" />
                </symbol>
                <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
                    <path
                        d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
                </symbol>
            </svg>
        </span>
    
        <div class="alert alert-primary d-flex align-items-center" role="alert">
            <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Info:">
                <use xlink:href="#info-fill" />
            </svg>
            <div>
                An example alert with an icon
            </div>
            <button type="button" class="btn-close ms-auto" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        <div class="alert alert-success d-flex align-items-center" role="alert">
            <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Success:">
                <use xlink:href="#check-circle-fill" />
            </svg>
            <div>
                An example success alert with an icon
            </div>
            <button type="button" class="btn-close ms-auto" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        <div class="alert alert-warning d-flex align-items-center" role="alert">
            <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Warning:">
                <use xlink:href="#exclamation-triangle-fill" />
            </svg>
            <div>
                An example warning alert with an icon
            </div>
            <button type="button" class="btn-close ms-auto" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        <div class="alert alert-danger d-flex align-items-center" role="alert">
            <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:">
                <use xlink:href="#exclamation-triangle-fill" />
            </svg>
            <div>
                An example danger alert with an icon
            </div>
            <button type="button" class="btn-close ms-auto" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    </div>
</div>


{% endblock %}

project/templates/project.html
{% extends 'base.html' %}